# 可以用 pod，也可以用 job
# Pod 创建后自动触发扩容
apiVersion: v1
kind: Pod
metadata:
  name: vpu-pri
  annotations:
    gke-gcsfuse/volumes: "true"
spec:
  restartPolicy: Never
  nodeSelector:
    cloud.google.com/gke-tpu-accelerator: tpu7x
    cloud.google.com/gke-tpu-topology: 2x2x1
  containers:
    - name: tpu-job
      image: python:3.12
      ports:
        - containerPort: 8431
      securityContext:
        privileged: false
      command:
        - bash
        - -c
        - |
          set -ex

          pip install -U --pre jax jaxlib libtpu requests -i https://us-python.pkg.dev/ml-oss-artifacts-published/jax/simple/ -f https://storage.googleapis.com/jax-releases/libtpu_releases.html

          pip list
          python -c 'import jax; print("Total TPU devices (cores):", jax.device_count())'

          git clone https://github.com/labyrinth-ssr/accelerator-microbenchmarks.git
          cd accelerator-microbenchmarks && git checkout bench-perf
          pip install -r requirements.txt

          sh ./Ironwood/scripts/vpu.sh

          cd /data/vpu-microbench
          tar -czf silu.tar.gz swiglu_fwd

          sleep infinity

      resources:
        requests:
          google.com/tpu: 4
        limits:
          google.com/tpu: 4
      volumeMounts:
        - name: gcs-fuse-csi-ephemeral
          mountPath: /data
          readOnly: false
  serviceAccountName: gcs-account
  volumes:
    - name: gcs-fuse-csi-ephemeral
      csi:
        driver: gcsfuse.csi.storage.gke.io
        readOnly: false
        volumeAttributes:
          bucketName: inference-model-storage-sgl
          mountOptions: "implicit-dirs"
