benchmarks:
  - benchmark_name: "gemm_multiple_run"
    trace_dir: "../data/microbench-1die/gemm_multiple_run_bf16"
    csv_path: "../data/microbench-1die/gemm_multiple_run_bf16"
    xlml_metrics_dir: "../data/microbench-1die/gemm_multiple_run_bf16"
    xla_dump_dir: "../data/microbench-1die/gemm_multiple_run_bf16/hlo_graphs"
    benchmark_sweep_params:
      - { m: 16384, k: 18432, n: 16384, num_runs: 100, dtype: "bfloat16" }
  - benchmark_name: "gemm_multiple_run"
    trace_dir: "../data/microbench-1die/gemm_multiple_run_fp8"
    csv_path: "../data/microbench-1die/gemm_multiple_run_fp8"
    xlml_metrics_dir: "../data/microbench-1die/gemm_multiple_run_fp8"
    xla_dump_dir: "../data/microbench-1die/gemm_multiple_run_fp8/hlo_graphs"
    benchmark_sweep_params:
      - { m: 16384, k: 18432, n: 16384, num_runs: 100, dtype: "float8" }
  - benchmark_name: "gemm_simple"
    trace_dir: "../data/microbench-1die/gemm_simple"
    csv_path: "../data/microbench-1die/gemm_simple"
    xlml_metrics_dir: "../data/microbench-1die/gemm_simple"
    xla_dump_dir: "../data/microbench-1die/gemm_simple/hlo_graphs"
    num_runs: 100
    benchmark_sweep_params:
      - { m: 16384, k: 18432, n: 16384 }
  - benchmark_name: "gemm"
    trace_dir: "../data/microbench-1die/gemm"
    csv_path: "../data/microbench-1die/gemm"
    xlml_metrics_dir: "../data/microbench-1die/gemm"
    xla_dump_dir: "../data/microbench-1die/gemm/hlo_graphs"
    num_runs: 100
    benchmark_sweep_params:
      - { m: 16384, k: 18432, n: 16384 }
  - benchmark_name: "gemm_accum"
    trace_dir: "../data/microbench-1die/gemm_accum"
    csv_path: "../data/microbench-1die/gemm_accum"
    xlml_metrics_dir: "../data/microbench-1die/gemm_accum"
    xla_dump_dir: "../data/microbench-1die/gemm_accum/hlo_graphs"
    num_runs: 100
    benchmark_sweep_params:
      - { m: 16384, k: 16384, n: 18432 }
  - benchmark_name: "quantization"
    trace_dir: "../data/microbench-1die/quantization"
    csv_path: "../data/microbench-1die/quantization"
    xlml_metrics_dir: "../data/microbench-1die/quantization"
    xla_dump_dir: "../data/microbench-1die/quantization/hlo_graphs"
    num_runs: 100
    benchmark_sweep_params:
      - { m: 16384, n: 16384 }
  - benchmark_name: "transpose_quantization"
    trace_dir: "../data/microbench-1die/transpose_quantization"
    csv_path: "../data/microbench-1die/transpose_quantization"
    xlml_metrics_dir: "../data/microbench-1die/transpose_quantization"
    xla_dump_dir: "../data/microbench-1die/transpose_quantization/hlo_graphs"
    num_runs: 100
    benchmark_sweep_params:
      - { m: 16384, n: 16384 }
  - benchmark_name: "add"
    trace_dir: "../data/microbench-1die/add"
    csv_path: "../data/microbench-1die/add"
    xlml_metrics_dir: "../data/microbench-1die/add"
    xla_dump_dir: "../data/microbench-1die/add/hlo_graphs"
    num_runs: 100
    benchmark_sweep_params:
      - { m: 4096, n: 16384 }
  - benchmark_name: "gemm_fp8_rowwise"
    trace_dir: "../data/microbench-1die/gemm_fp8_rowwise"
    csv_path: "../data/microbench-1die/gemm_fp8_rowwise"
    xlml_metrics_dir: "../data/microbench-1die/gemm_fp8_rowwise"
    xla_dump_dir: "../data/microbench-1die/gemm_fp8_rowwise/hlo_graphs"
    num_runs: 100
    benchmark_sweep_params:
      - { m: 16384, k: 16384, n: 4096 }
