benchmarks:
  - benchmark_name: "gemm_mxfp8_b32_static_scaling"
    trace_dir: "../data/microbenchmarks/gemm_mxfp8_b32_static_scaling"
    csv_path: "../data/microbenchmarks/gemm_mxfp8_b32_static_scaling"
    xlml_metrics_dir: "../data/microbenchmarks/gemm_mxfp8_b32_static_scaling"
    xla_dump_dir: "../data/microbenchmarks/gemm_mxfp8_b32_static_scaling/hlo_graphs"
    num_runs: 100
    benchmark_sweep_params:
      - { m: 16384, k: 16384, n: 4096 }
      - { m: 4096, k: 16384, n: 16384 }
      - { m: 16384, k: 16384, n: 16384 }
      - { m: 1024, k: 16384, n: 4096 }
      - { m: 4096, k: 16384, n: 1024 }
      - { m: 1024, k: 16384, n: 1024 }
      - { m: 16384, k: 1024, n: 4096 }
      - { m: 4096, k: 1024, n: 16384 }
      - { m: 16384, k: 1024, n: 16384 }
      - { m: 1024, k: 1024, n: 4096 }
      - { m: 4096, k: 1024, n: 1024 }
      - { m: 1024, k: 1024, n: 1024 }
