benchmarks:
  - benchmark_name: "gemm_multiple_run"
    trace_dir: "../data/microbenchmarks/gemm_multiple_run_bf16"
    csv_path: "../data/microbenchmarks/gemm_multiple_run_bf16"
    xlml_metrics_dir: "../data/microbenchmarks/gemm_multiple_run_bf16"
    xla_dump_dir: "../data/microbenchmarks/gemm_multiple_run_bf16/hlo_graphs"
    benchmark_sweep_params:
      - { m: 16384, k: 18432, n: 16384, num_runs: 100, dtype: "bfloat16" }
  - benchmark_name: "gemm_multiple_run"
    trace_dir: "../data/microbenchmarks/gemm_multiple_run_fp8"
    csv_path: "../data/microbenchmarks/gemm_multiple_run_fp8"
    xlml_metrics_dir: "../data/microbenchmarks/gemm_multiple_run_fp8"
    xla_dump_dir: "../data/microbenchmarks/gemm_multiple_run_fp8/hlo_graphs"
    benchmark_sweep_params:
      - { m: 16384, k: 18432, n: 16384, num_runs: 100, dtype: "float8" }
