benchmarks:
  - benchmark_name: "gemm_simple"
    trace_dir: "../data/microbench-1die/gemm_simple"
    csv_path: "../data/microbench-1die/gemm_simple"
    xlml_metrics_dir: "../data/microbench-1die/gemm_simple"
    xla_dump_dir: "../data/microbench-1die/gemm_simple/hlo_graphs"
    num_runs: 100
    benchmark_sweep_params:
      - { m: 16384, k: 18432, n: 16384 }
  - benchmark_name: "gemm"
    trace_dir: "../data/microbench-1die/gemm"
    csv_path: "../data/microbench-1die/gemm"
    xlml_metrics_dir: "../data/microbench-1die/gemm"
    xla_dump_dir: "../data/microbench-1die/gemm/hlo_graphs"
    num_runs: 100
    benchmark_sweep_params:
      - { m: 16384, k: 18432, n: 16384 }
  - benchmark_name: "gemm_accum"
    trace_dir: "../data/microbench-1die/gemm_accum"
    csv_path: "../data/microbench-1die/gemm_accum"
    xlml_metrics_dir: "../data/microbench-1die/gemm_accum"
    xla_dump_dir: "../data/microbench-1die/gemm_accum/hlo_graphs"
    num_runs: 100
    benchmark_sweep_params:
      - { m: 16384, k: 16384, n: 18432 }
  - benchmark_name: "quantization"
    trace_dir: "../data/microbench-1die/quantization"
    csv_path: "../data/microbench-1die/quantization"
    xlml_metrics_dir: "../data/microbench-1die/quantization"
    xla_dump_dir: "../data/microbench-1die/quantization/hlo_graphs"
    num_runs: 100
    benchmark_sweep_params:
      - { m: 16384, n: 16384 }
  - benchmark_name: "transpose_quantization"
    trace_dir: "../data/microbench-1die/transpose_quantization"
    csv_path: "../data/microbench-1die/transpose_quantization"
    xlml_metrics_dir: "../data/microbench-1die/transpose_quantization"
    xla_dump_dir: "../data/microbench-1die/transpose_quantization/hlo_graphs"
    num_runs: 100
    benchmark_sweep_params:
      - { m: 16384, n: 16384 }
  - benchmark_name: "quantization_static_scaling"
    trace_dir: "../data/microbench-1die/quantization_static_scaling"
    csv_path: "../data/microbench-1die/quantization_static_scaling"
    xlml_metrics_dir: "../data/microbench-1die/quantization_static_scaling"
    xla_dump_dir: "../data/microbench-1die/quantization_static_scaling/hlo_graphs"
    num_runs: 100
    benchmark_sweep_params:
      - { m: 16384, n: 16384 }
  - benchmark_name: "transpose_quantization_static_scaling"
    trace_dir: "../data/microbench-1die/transpose_quantization_static_scaling"
    csv_path: "../data/microbench-1die/transpose_quantization_static_scaling"
    xlml_metrics_dir: "../data/microbench-1die/transpose_quantization_static_scaling"
    xla_dump_dir: "../data/microbench-1die/transpose_quantization_static_scaling/hlo_graphs"
    num_runs: 100
    benchmark_sweep_params:
      - { m: 16384, n: 16384 }
  - benchmark_name: "swiglu_fwd"
    trace_dir: "../data/microbench-1die/swiglu_fwd"
    csv_path: "../data/microbench-1die/swiglu_fwd"
    xlml_metrics_dir: "../data/microbench-1die/swiglu_fwd"
    xla_dump_dir: "../data/microbench-1die/swiglu_fwd/hlo_graphs"
    num_runs: 100
    benchmark_sweep_params:
      - { m: 8192, n: 8192 }
  - benchmark_name: "swiglu_bwd"
    trace_dir: "../data/microbench-1die/swiglu_bwd"
    csv_path: "../data/microbench-1die/swiglu_bwd"
    xlml_metrics_dir: "../data/microbench-1die/swiglu_bwd"
    xla_dump_dir: "../data/microbench-1die/swiglu_bwd/hlo_graphs"
    num_runs: 100
    benchmark_sweep_params:
      - { m: 8192, n: 8192 }
  - benchmark_name: "rmsnorm_fwd"
    trace_dir: "../data/microbench-1die/rmsnorm_fwd"
    csv_path: "../data/microbench-1die/rmsnorm_fwd"
    xlml_metrics_dir: "../data/microbench-1die/rmsnorm_fwd"
    xla_dump_dir: "../data/microbench-1die/rmsnorm_fwd/hlo_graphs"
    num_runs: 100
    benchmark_sweep_params:
      - { m: 4096, n: 16384 }
  - benchmark_name: "rmsnorm_bwd"
    trace_dir: "../data/microbench-1die/rmsnorm_bwd"
    csv_path: "../data/microbench-1die/rmsnorm_bwd"
    xlml_metrics_dir: "../data/microbench-1die/rmsnorm_bwd"
    xla_dump_dir: "../data/microbench-1die/rmsnorm_bwd/hlo_graphs"
    num_runs: 100
    benchmark_sweep_params:
      - { m: 4096, n: 16384 }
  - benchmark_name: "add"
    trace_dir: "../data/microbench-1die/add"
    csv_path: "../data/microbench-1die/add"
    xlml_metrics_dir: "../data/microbench-1die/add"
    xla_dump_dir: "../data/microbench-1die/add/hlo_graphs"
    num_runs: 100
    benchmark_sweep_params:
      - { m: 4096, n: 16384 }
  - benchmark_name: "gemm_fp8_rowwise"
    trace_dir: "../data/microbench-1die/gemm_fp8_rowwise"
    csv_path: "../data/microbench-1die/gemm_fp8_rowwise"
    xlml_metrics_dir: "../data/microbench-1die/gemm_fp8_rowwise"
    xla_dump_dir: "../data/microbench-1die/gemm_fp8_rowwise/hlo_graphs"
    num_runs: 100
    benchmark_sweep_params:
      - { m: 16384, k: 16384, n: 4096 }
  - benchmark_name: "gemm_fp8_b128_fp32"
    trace_dir: "../data/microbench-1die/gemm_fp8_b128_fp32"
    csv_path: "../data/microbench-1die/gemm_fp8_b128_fp32"
    xlml_metrics_dir: "../data/microbench-1die/gemm_fp8_b128_fp32"
    xla_dump_dir: "../data/microbench-1die/gemm_fp8_b128_fp32/hlo_graphs"
    num_runs: 100
    benchmark_sweep_params:
      - { m: 16384, k: 16384, n: 4096 }
  - benchmark_name: "gemm_fp8_rowwise_static_scaling"
    trace_dir: "../data/microbench-1die/gemm_fp8_rowwise_static_scaling"
    csv_path: "../data/microbench-1die/gemm_fp8_rowwise_static_scaling"
    xlml_metrics_dir: "../data/microbench-1die/gemm_fp8_rowwise_static_scaling"
    xla_dump_dir: "../data/microbench-1die/gemm_fp8_rowwise_static_scaling/hlo_graphs"
    num_runs: 100
    benchmark_sweep_params:
      - { m: 16384, k: 16384, n: 4096 }
  - benchmark_name: "gemm_fp8_b128_fp32_static_scaling"
    trace_dir: "../data/microbench-1die/gemm_fp8_b128_fp32_static_scaling"
    csv_path: "../data/microbench-1die/gemm_fp8_b128_fp32_static_scaling"
    xlml_metrics_dir: "../data/microbench-1die/gemm_fp8_b128_fp32_static_scaling"
    xla_dump_dir: "../data/microbench-1die/gemm_fp8_b128_fp32_static_scaling/hlo_graphs"
    num_runs: 100
    benchmark_sweep_params:
      - { m: 16384, k: 16384, n: 4096 }
  - benchmark_name: "gemm_mxfp8_b32"
    trace_dir: "../data/microbench-1die/gemm_mxfp8_b32"
    csv_path: "../data/microbench-1die/gemm_mxfp8_b32"
    xlml_metrics_dir: "../data/microbench-1die/gemm_mxfp8_b32"
    xla_dump_dir: "../data/microbench-1die/gemm_mxfp8_b32/hlo_graphs"
    num_runs: 100
    benchmark_sweep_params:
      - { m: 16384, k: 16384, n: 4096 }
  - benchmark_name: "gemm_mxfp8_b32_static_scaling"
    trace_dir: "../data/microbench-1die/gemm_mxfp8_b32_static_scaling"
    csv_path: "../data/microbench-1die/gemm_mxfp8_b32_static_scaling"
    xlml_metrics_dir: "../data/microbench-1die/gemm_mxfp8_b32_static_scaling"
    xla_dump_dir: "../data/microbench-1die/gemm_mxfp8_b32_static_scaling/hlo_graphs"
    num_runs: 100
    benchmark_sweep_params:
      - { m: 16384, k: 16384, n: 4096 }
