benchmarks:
  - benchmark_name: "gemm_throttling"
    trace_dir: "../data/microbenchmarks/gemm_throttling_data_gen_once_noblock"
    csv_path: "../data/microbenchmarks/gemm_throttling_data_gen_once_noblock"
    xlml_metrics_dir: "../data/microbenchmarks/gemm_throttling_data_gen_once_noblock"
    xla_dump_dir: "../data/microbenchmarks/gemm_throttling_data_gen_once_noblock/hlo_graphs"
    benchmark_sweep_params:
      - {
          m: 16384,
          k: 18432,
          n: 16384,
          num_runs: 10000,
          dtype: "float8",
          gap_strategy: "data_gen_once_noblock",
        }
