benchmarks:
  - benchmark_name: "gemm_simple_with_dtype"
    trace_dir: "../data/microbench-1die/gemm_simple_inference"
    csv_path: "../data/microbench-1die/gemm_simple_inference"
    xlml_metrics_dir: "../data/microbench-1die/gemm_simple_inference"
    num_runs: 1000
    benchmark_sweep_params:
      - {
          m: { start: 1, end: 65536, multiplier: 2 },
          k: { start: 128, end: 65536, multiplier: 2 },
          n: { start: 128, end: 65536, multiplier: 2 },
          in_dtype_str: "bf16",
          out_dtype_str: "bf16",
        }
      - {
          m: { start: 1, end: 65536, multiplier: 2 },
          k: { start: 128, end: 65536, multiplier: 2 },
          n: { start: 128, end: 65536, multiplier: 2 },
          in_dtype_str: "fp8",
          out_dtype_str: "bf16",
        }
