benchmarks:
  - benchmark_name: all_to_all
    benchmark_sweep_params:
      - {
          matrix_dim_range: { start: 256, end: 32768, multiplier: 2 },
          dtype: "float32",
          mesh_shape: "2x4x1",
          ici_size: 8,
          sharding_strategy: "1x4x1", # Only d_1 axis (4 devices)
          op_dimension: 1,
          num_runs: 5,
        }
      - {
          matrix_dim_range: { start: 256, end: 32768, multiplier: 2 },
          dtype: "float32",
          mesh_shape: "1x2x4",
          ici_size: 8,
          sharding_strategy: "1x1x4", # Only d_0 axis (2 devices)
          op_dimension: 1,
          num_runs: 5,
        }
      - {
          matrix_dim_range: { start: 256, end: 32768, multiplier: 2 },
          dtype: "float32",
          op_dimension: 1,
          num_runs: 5,
          mesh_shape: "2x2x2",
          ici_size: 8,
          sharding_strategy: "2x1x1", # Only d_0 (2-way)
        }
      - {
          matrix_dim_range: { start: 256, end: 32768, multiplier: 2 },
          dtype: "float32",
          op_dimension: 1,
          num_runs: 5,
          mesh_shape: "8x1x1",
          ici_size: 8,
          sharding_strategy: "8x1x1", # All 8 devices in one line
        }
    trace_dir: "../data/collectives/all_to_all_1d"
    csv_path: "../data/collectives/all_to_all_1d"
    xlml_metrics_dir: "../data/collectives/all_to_all_1d"
    xla_dump_dir: "../data/collectives/all_to_all_1d/hlo_graphs"
