benchmarks:
  - benchmark_name: all_gather
    benchmark_sweep_params:
      # - {
      #     matrix_dim_range: { start: 2, end: 8192, multiplier: 2 },
      #     dtype: "float32",
      #     mesh_shape: "2x4x1",
      #     ici_size: 8,
      #     sharding_strategy: "1x4x1", # Only d_1 axis (4 devices)
      #     op_dimension: 1,
      #     num_runs: 5,
      #   }
      # - {
      #     matrix_dim_range: { start: 2, end: 8192, increase_by: 60 },
      #     dtype: "float32",
      #     mesh_shape: "2x4x1",
      #     ici_size: 8,
      #     sharding_strategy: "1x4x1", # Only d_1 axis (4 devices)
      #     op_dimension: 1,
      #     num_runs: 5,
      #   }
      # - {
      #     matrix_dim_range: { start: 2, end: 8192, multiplier: 2 },
      #     dtype: "float32",
      #     mesh_shape: "4x2x1",
      #     ici_size: 8,
      #     sharding_strategy: "4x1x1", # Only d_0 axis (2 devices)
      #     op_dimension: 1,
      #     num_runs: 5,
      #   }
      # - {
      #     matrix_dim_range: { start: 2, end: 8192, increase_by: 60 },
      #     dtype: "float32",
      #     mesh_shape: "4x2x1",
      #     ici_size: 8,
      #     sharding_strategy: "4x1x1", # Only d_0 axis (2 devices)
      #     op_dimension: 1,
      #     num_runs: 5,
      #   }
      # - {
      #     matrix_dim_range: { start: 2, end: 8192, multiplier: 2 },
      #     dtype: "float32",
      #     op_dimension: 1,
      #     num_runs: 5,
      #     mesh_shape: "2x2x2",
      #     ici_size: 8,
      #     sharding_strategy: "2x1x1", # Only d_0 (2-way)
      #   }
      # - {
      #     matrix_dim_range: { start: 2, end: 8192, increase_by: 60 },
      #     dtype: "float32",
      #     op_dimension: 1,
      #     num_runs: 5,
      #     mesh_shape: "2x2x2",
      #     ici_size: 8,
      #     sharding_strategy: "2x1x1", # Only d_0 (2-way)
      #   }
      # - {
      #     matrix_dim_range: { start: 2, end: 8192, multiplier: 2 },
      #     dtype: "float32",
      #     op_dimension: 1,
      #     num_runs: 5,
      #     mesh_shape: "8x1x1",
      #     ici_size: 8,
      #     sharding_strategy: "8x1x1", # All 8 devices in one line
      #   }
      - {
          matrix_dim: 4196,
          dtype: "float32",
          op_dimension: 1,
          num_runs: 5,
          mesh_shape: "8x1x1",
          ici_size: 8,
          sharding_strategy: "8x1x1", # All 8 devices in one line
        }
      # - {
      #     matrix_dim: 5596,
      #     dtype: "float32",
      #     op_dimension: 1,
      #     num_runs: 5,
      #     mesh_shape: "8x1x1",
      #     ici_size: 8,
      #     sharding_strategy: "8x1x1", # All 8 devices in one line
      #   }

      # - {
      #     matrix_dim_range: { start: 1, end: 256, increase_by: 20 },
      #     dtype: "float32",
      #     op_dimension: 1,
      #     num_runs: 1,
      #     mesh_shape: "8x1x1",
      #     ici_size: 8,
      #     sharding_strategy: "8x1x1", # All 8 devices in one line
      #   }
      # - {
      #     matrix_dim_range: { start: 256, end: 1024, increase_by: 30 },
      #     dtype: "float32",
      #     op_dimension: 1,
      #     num_runs: 5,
      #     mesh_shape: "8x1x1",
      #     ici_size: 8,
      #     sharding_strategy: "8x1x1", # All 8 devices in one line
      #   }
      # - {
      #     matrix_dim_range: { start: 2, end: 8192, multiplier: 2 },
      #     dtype: "bfloat16",
      #     op_dimension: 1,
      #     num_runs: 5,
      #     mesh_shape: "8x1x1",
      #     ici_size: 8,
      #     sharding_strategy: "8x1x1", # All 8 devices in one line
      #   }
    trace_dir: "/tmp/all_gather_1d"
    csv_path: "/tmp/all_gather_1d"
    xlml_metrics_dir: "/tmp/all_gather_1d"
    xla_dump_dir: "/tmp/all_gather_1d/hlo_graphs"
