benchmarks:
  - benchmark_name: all_gather
    benchmark_sweep_params:
      - {
          matrix_dim: 4096,
          dtype: "float32",
          mesh_shape: "4x2x2x2",
          ici_size: 32,
          sharding_strategy: "4x2x2x1", # Only d_1 axis (4 devices)
          op_dimension: 3,
          num_runs: 5,
        }
      - {
          matrix_dim: 4096,
          dtype: "float32",
          mesh_shape: "4x2x2x2",
          ici_size: 32,
          sharding_strategy: "4x2x2x2", # Only d_1 axis (4 devices)
          op_dimension: 3,
          num_runs: 5,
        }
    trace_dir: "/tmp/collectives/all_gather_3d"
    csv_path: "/tmp/collectives/all_gather_3d"
    xlml_metrics_dir: "/tmp/collectives/all_gather_3d"
    xla_dump_dir: "/tmp/collectives/all_gather_3d/hlo_graphs"
