benchmarks:
  - benchmark_name: psum
    benchmark_sweep_params:
      - {
          matrix_dim_range: { start: 256, end: 32768, multiplier: 2 },
          dtype: "float32",
          op_dimension: 1,
          num_runs: 5,
          mesh_shape: "2x2x2",
          ici_size: 8,
          sharding_strategy: "2x2x2", # Only d_0 (2-way)
        }
    trace_dir: "../data/collectives/all_reduce_3d"
    csv_path: "../data/collectives/all_reduce_3d"
    xlml_metrics_dir: "../data/collectives/all_reduce_3d"
    xla_dump_dir: "../data/collectives/all_reduce_3d/hlo_graphs"
