apiVersion: v1
kind: Pod
metadata:
  name: hbm
spec:
  restartPolicy: Never
  nodeSelector:
    cloud.google.com/gke-tpu-accelerator: tpu7x
    cloud.google.com/gke-tpu-topology: 2x2x1
  containers:
    - name: tpu-job
      image: python:3.12
      ports:
        - containerPort: 8431
      securityContext:
        privileged: false
      command:
        - bash
        - -c
        - |
          set -ex

          git clone https://github.com/AI-Hypercomputer/accelerator-microbenchmarks.git
          cd accelerator-microbenchmarks
          pip install -r requirements.txt

          python Ironwood/src/run_benchmark.py --config="Ironwood/configs/hbm/hbm.yaml"

          tar -czf hbm.tar.gz /data/microbench-1die/hbm

          sleep infinity

      resources:
        requests:
          google.com/tpu: 4
        limits:
          google.com/tpu: 4

      volumeMounts:
        - name: gcs-fuse-csi-ephemeral
          mountPath: /data
          readOnly: false
  serviceAccountName: gcs-account
  volumes:
    - name: gcs-fuse-csi-ephemeral
      csi:
        driver: gcsfuse.csi.storage.gke.io
        readOnly: false
        volumeAttributes:
          bucketName: model-storage-sglang
          mountOptions: "implicit-dirs"
